<div style="line-height: 24px; padding: 20px; font-size: 16px; word-wrap: break-word; font-family: arial, helvetica, sans-serif;">

<!-- Two-Column: Message / Shipping -->
<table width="100%" cellpadding="0" cellspacing="0" role="presentation"
       style="max-width:700px;margin:0 auto;border-collapse:collapse;font-family:Arial,Helvetica,sans-serif;color:#151515;">

    <!-- TOP INFO ROW -->
    <tr>
        <td width="50%" style="padding:10px 12px;border-bottom:1px solid #e6e6e6;">
            <div style="font-size:13px;color:#777777;">Giftcard Generated By</div>
            <div style="font-size:15px;font-weight:bold;padding-top:4px;">
                {{ $maildata->your_name }}
            </div>
        </td>
        <td width="50%" style="padding:10px 12px;border-bottom:1px solid #e6e6e6;">
            <div style="font-size:13px;color:#777777;">Gifted To</div>
            <div style="font-size:15px;font-weight:bold;padding-top:4px;">
                {{ $maildata->recipient_name }}
            </div>
        </td>
    </tr>

    <!-- SPACING -->
    <tr><td colspan="2" height="16">&nbsp;</td></tr>

    <!-- CONTENT ROW -->
    <tr>
        <!-- MESSAGE -->
        <td valign="top" width="50%" style="padding:12px;">
            <table width="100%" cellpadding="0" cellspacing="0" role="presentation"
                   style="border:1px solid #e6e6e6;border-radius:6px;">
                <tr>
                    <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;
                               font-size:14px;font-weight:bold;">
                        💬 Message
                    </td>
                </tr>
                <tr>
                    <td style="padding:14px 12px;
                               font-size:15px;
                               line-height:24px;
                               color:#555555;">
                        Wishing you a wonderful birthday filled with joy and laughter!
                    </td>
                </tr>
            </table>
        </td>

        <!-- SHIPPING -->
        <td valign="top" width="50%" style="padding:12px;">
            <table width="100%" cellpadding="0" cellspacing="0" role="presentation"
                   style="border:1px solid #e6e6e6;border-radius:6px;">
                <tr>
                    <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;
                               font-size:14px;font-weight:bold;">
                        📦 Shipping
                    </td>
                </tr>
                <tr>
                    <td style="padding:14px 12px;
                               font-size:15px;
                               line-height:24px;
                               color:#555555;">
                        The gift card will be sent to<br>
                        <strong style="color:#000000;"> {{ $maildata->recipient_name }}</strong>
                        <br><br>
                        Addressed to<br>
                        <strong style="color:#000000;"> {{ $maildata->your_name }}</strong>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</div>
