@php
    $isDummyMode = request()->query('mode') === 'dummy';
@endphp

@if ($isDummyMode)
    @php
        /*
         |-----------------------------------------
         | Dummy preview data (ONLY for preview)
         |-----------------------------------------
         */
       
        $cardnumber = [
            (object) ['giftnumber' => 'GIFT-1234567890'],
            (object) ['giftnumber' => 'GIFT-0987654321'],
            (object) ['giftnumber' => 'GIFT-0987654323'],
            (object) ['giftnumber' => 'GIFT-0987654324'],
        ];  
    @endphp
@else
    @php
        /*
         |-----------------------------------------
         | Real data passed from controller
         |-----------------------------------------
         */
        $cardnumber = App\Models\GiftcardsNumbers::where('transaction_id', $maildata->transaction_id)->get();
    @endphp
@endif
<div style="line-height: 24px; padding: 20px; font-size: 16px; word-wrap: break-word; font-family: arial, helvetica, sans-serif;">

<!-- Two-Column: Message / Shipping -->
<table width="100%" cellpadding="0" cellspacing="0" role="presentation"
       style="max-width:700px;margin:0 auto;border-collapse:collapse;font-family:Arial,Helvetica,sans-serif;color:#151515;">

    <!-- TOP INFO ROW -->
    <tr>
        <td width="50%" style="padding:10px 12px;border-bottom:1px solid #e6e6e6;">
            <div style="font-size:13px;color:#777777;">Giftcard Generated By</div>
            <div style="font-size:15px;font-weight:bold;padding-top:4px;">
                {{ $maildata->your_name }}
            </div>
        </td>
        <td width="50%" style="padding:10px 12px;border-bottom:1px solid #e6e6e6;">
            <div style="font-size:13px;color:#777777;">Gifted To</div>
            <div style="font-size:15px;font-weight:bold;padding-top:4px;">
                {{ $maildata->recipient_name }}
            </div>
        </td>
    </tr>

    <!-- SPACING -->
    <tr><td colspan="2" height="16">&nbsp;</td></tr>

    <!-- CONTENT ROW -->
    <tr>
        <!-- MESSAGE -->
        <td valign="top" width="50%" style="padding:12px;">
            <table width="100%" cellpadding="0" cellspacing="0" role="presentation"
                   style="border:1px solid #e6e6e6;border-radius:6px;">
                <tr>
                    <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;
                               font-size:14px;font-weight:bold;">
                        💬 Message
                    </td>
                </tr>
                <tr>
                    <td style="padding:14px 12px;
                               font-size:15px;
                               line-height:24px;
                               color:#555555;">
                                {{ $maildata->message }}
                       
                    </td>
                </tr>
            </table>
        </td>

        <!-- SHIPPING -->
        <td valign="top" width="50%" style="padding:12px;">
            <table width="100%" cellpadding="0" cellspacing="0" role="presentation"
                   style="border:1px solid #e6e6e6;border-radius:6px;">
                <tr>
                    <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;
                               font-size:14px;font-weight:bold;">
                        📦 Shipping
                    </td>
                </tr>
                <tr>
                    <td style="padding:14px 12px;
                               font-size:15px;
                               line-height:24px;
                               color:#555555;">
                        The gift card will be sent to<br>
                        <strong style="color:#000000;"> {{ $maildata->recipient_name }}</strong>
                        <br><br>
                        
                    </td>
                </tr>
            </table>
        </td>
    </tr>


    
</table>



<table id="u_content_heading_2" style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0"
    cellspacing="0" width="100%" border="0">
    <tbody>
        <tr>
            <td style="overflow-wrap:break-word;word-break:break-word;padding:30px 0px 0px;font-family:arial,helvetica,sans-serif;"
                align="left">
                
                <h1 class="v-line-height v-font-size"
                    style="margin: 0px; color: #000000; line-height: 140%; text-align: center; word-wrap: break-word; font-family: Epilogue; font-size: 40px; font-weight: 700;">
                    Giftcard Details:
                </h1>

            </td>
        </tr>
        {{-- Gift Card Generate --}}
        <tr>
            <td>
                @foreach ($cardnumber as $value)
                    <tr>
    <td align="center" style="padding:20px 0;">
        @foreach ($cardnumber as $value)
            <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                <tr>
                    <td align="center" style="padding:10px 0;">
                        <table width="600" cellpadding="0" cellspacing="0" role="presentation"
                               style="margin:0 auto;">
                            <tr>
                                <td align="center">
                                    <span
                                        style="
                                            display:inline-block;
                                            padding:12px 28px;
                                            font-size:20px;
                                            font-family:Arial, Helvetica, sans-serif;
                                            font-weight:bold;
                                            color:#ffffff;
                                            background-color:#fca52a;
                                            border-radius:6px;
                                            letter-spacing:1px;
                                        ">
                                        {{ $value->giftnumber }}
                                    </span>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        @endforeach
    </td>
</tr>

                @endforeach
            </td>
        </tr>
    </tbody>
</table>

</div>
